### ISSUE TITLE
enable GloBI inclusion by adding "http://globalbioticinteractions.org" in the readme

### ISSUE THREAD

**Issue by jhpoelen** [millerse/BHL-Interactions#1]
Hi @millerse, I noticed that the readme of this dataset doesn't include the term "http://globalbioticinteractions.org". Only if this is included, GloBI will used it. Suggest to include the term.

**Comment by millerse** [comment]
Sorry about that.  I will take care of that.

**Comment by jhpoelen** [comment]
@millerse thanks!
