### ISSUE TITLE
suggest to use hasPathogen instead of hostOf 

### ISSUE THREAD

**Issue by jhpoelen** [millerse/BHL-Interactions#2]
When looking for pathogen of bananas and plantains (Musa), I was happy to find that the Panama disease was present in the BHL interactions datasets. 

Currently (see https://github.com/jhpoelen/eol-globi-data/issues/156) the interaction is reported as a "hostOf" interaction ([RO:0002453](http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/RO_0002453) ).

I was wondering whether the interaction can be described more accurately by using the "hasPathogen" interaction [RO:0002557](http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/RO_0002557). If so, I think it would make it easier to find the relevant interaction and related reference.

@millerse curious to hear your thoughts on this.

**Comment by millerse** [comment]
@jhpoelen Sure.  The way that the data was presented in the book (using banana and Panama dissease) was the banana was the host of Panama disease.  If you think the data would be better presented as hasPathogen then I am fine with that.

**Comment by jhpoelen** [comment]
@millerse if you believe that the term "host" in the book referred to a pathogen-host interaction, I would suggest using the interaction hasPathogen (or its inverse pathogenOf). Reason is that the interaction type "hostOf" could refer to a host-pathogen, host-parasite or any other host-\* interaction. However, if you believe that this misrepresents the context if which the term "host" was used, I'd suggest to leave as is. Curious to hear what you end up settling with.

**Comment by millerse** [comment]
@jhpoelen After talking with Katja and Jen, we decided hasPathogen is a better description of the interaction.  Links have been fixed.

**Comment by jhpoelen** [comment]
@millerse thank you for being thorough!
