### ISSUE TITLE
lines 2816-2824 use suspicious id/name "EOL:32480393"/"Leaf roll (Corium solani Holmes, Solanum virus 14"

### ISSUE THREAD

**Issue by jhpoelen** [millerse/BHL-Interactions#3]
discovered during integrity checking of GloBI taxon archives.

Suggest to consider using an alternate, recognized name for the virus, perhaps reverting to a higher order taxon. Minimally, use the scientific name rather than common/scientific name combo.

Hope this helps!

**Comment by millerse** [comment]
Fixed.  Thanks for the heads up
